pluginName: diy

apps:
  apis:
  - tiangou: true
  - saucenao: true
  - randomPixivImg: true
  - shareMusic: true
  - blueArchive: true

  cmd:
  - cmd: true

  main:
  - ahelp: true
  - recall: false
  - what2eat: true

  gachaCalculator:
  - gachaCalculator: true

  tarot:
  - tarot: true

  schedule:
  - todayNews: true

  chat:
  - chat: true

  dice:
  - dice: true

# 部分功能的配置关系, 作用于 default, config 文件夹内命名方式, 一般不需要改动
configs:
  index:
  - config

  schedule:
  - todayNews
  - func

  chat:
  - chat

  tarot:
  - tarot
