# 每个功能对应开关, -true 启用, -false 关闭
apps:
  apis:
    - tiangou: true
    - saucenao: true
    - randomImg: true
    - shareMusic: true
    - riskValue: true

  cmd:
    - cmd: true

  main:
    - ahelp: true
    - recall: false
    - tarot: true
    - what2eat: true
    - dice: true
    - gachaSupport: true

  schedule:
    - todayNews: true

  chat:
    - chat: true

  test:
    - test: true

# 部分功能的配置关系, 作用于 default, config 文件夹内命名方式, 一般不需要改动
configs:
  index:
    - config

  schedule:
    - todayNews

  chat:
    - chat