# 每日简报公共推送定时任务
scheduleTime: 0 0 8 * * ?

# *- 任意值
# ?- 不指定，仅日期和星期域支持该字符
# Cron表达式
#     *  *  *  *  *  *
#     ┬  ┬  ┬  ┬  ┬  ┬
#     │  │  │  │  │  |
#     │  │  │  │  │  └ 星期几，取值：0 - 7，其中 0 和 7 都表示是周日
#     │  │  │  │  └─── 月份，取值：1 - 12
#     │  │  │  └────── 日期，取值：1 - 31
#     │  │  └───────── 时，取值：0 - 23
#     │  └──────────── 分，取值：0 - 59
#     └─────────────── 秒，取值：0 - 59（可选）

#     e.g. time = '0 30 8 * * ?'
#     表示每日 08:30:00

#公共推送群
: []

#资讯推送群
Group2: []